config/routes.rb
Rails.application.routes.draw do
  get '/refresh' => 'main#refresh'
  root 'main#index'
  get '/modal_content/:type/:id' => 'main#modal_content'

  get '/d_day', to: 'main#d_day'
  get '/search', to: "main#search"
  
  post '/ad_like/:ad_id', to: 'likes#like_toggle'

  resources :market_posts do
    resources :market_comments, only: [:create, :destroy]
  end
  post '/market_posts/:market_post_id/reply/:id', to: 'market_comments#reply', as: 'market_post_reply'


  resources :ads, except: [:show]


  get '/intro', to: 'main#intro'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'} 

  get 'managers/my_adballoon', to: 'managers#my_adballoon'

  get 'managers/index', to: 'managers#index'
  get 'managers/ad_list', to: 'managers#ad_list'
  get 'managers/user_list', to: 'managers#user_list'
  
  get 'managers/ads/:id', to: 'managers#ads_edit', as: 'managers_ads'
  patch 'managers/ads/:id', to: 'managers#ads_update'
  delete 'managers/ads/:id', to: 'managers#ads_delete'

  post 'managers/ad_img/:id', to: 'managers#img_update', as: 'managers_img'
  post 'managers/ad_toggle/:id', to: 'managers#ad_toggle', as: 'managers_ad_toggle'

  get 'managers/main'
  post 'managers/main_update/:type', to: 'managers#main_update'
  post 'managers/ad_check/:id', to: 'managers#ad_check'
  post 'managers/img_update/:id', to: 'managers#img_update'
  delete 'managers/ads_delete/:id', to: 'managers#ads_delete'
end

app/models/ad.rb
class Ad < ApplicationRecord
  mount_uploader :img, ImgUploader
  mount_uploader :temp_img, ImgUploader
  mount_uploader :banner_img, ImgUploader
  mount_uploader :temp_banner_img, ImgUploader
     
  # TODO : start_date, end_date, announced_link / banner_date, recommend_date 날짜 유효성 검사
  has_and_belongs_to_many :hashtags
  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  VALID_PHONE_NUMBER_REGEX = /\A010(\d{3}|\d{4})\d{4}\z/
  VALID_URL = URI.regexp


  serialize :detail_method, Array
  serialize :detail_prize, Array

  validates :company, 
            :businessLicenseNumber, 
            :title, 
            :detail_prize, presence: true

  validates :ad_type, presence: true, 
                      inclusion: { in: ["event", "coupon"] }

  validates :phone, presence: true,
                    format: { with: VALID_PHONE_NUMBER_REGEX }
 
  validates :main_type, presence: true,
                        inclusion: { in: [0, 1, 2, 3] }


  validates :link, presence: true,
                   format: { with: VALID_URL }

  validates :method, 
            :detail_method, 
            :announced_link, 
            :announced_date, presence: { if: -> { self.ad_type == "event" } }

  # validates :announced_link, format: { with: VALID_URL }

  validates :etc_message, presence: { if: -> { self.ad_type == "coupon" } }

  # validates :img, presence: true#, format: { with: /.\.(png|jpeg|jpg|gif)\z/ }
  # # :banner_img, :temp_img, :temp_banner_img, if not_nil, format: { with: /.\.(png|jpeg|jpg|gif)\z/ }

  # validates :banner_img, presence: { if: -> { !self.temp_banner_img.nil? } }

  # validates :banner_frequency,
  #           :banner_date, presence: { if: -> { !self.banner_img.nil? } }
  # validates :recommend_frequency,
  #           :recommend_date, presence: { if: -> { !self.banner_img.nil? } }

  validates :banner_frequency, 
            :recommend_frequency, inclusion: { in: [nil, 0, 1] }

  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_date_is_after_start_date
  validate :announced_date_is_after_end_date

  
  def detail_method_to_a
    self.detail_method.class.to_s != 'Array' ? JSON.parse(self.detail_method) : self.detail_method
  end  
  def detail_prize_to_a
    self.detail_prize.class.to_s != 'Array' ? JSON.parse(self.detail_prize) : self.detail_prize
  end
  
  def start_time
    self.banner_date
  end 
  def end_time
    if self.banner_frequency == 0
      self.banner_date + 6.days
    else
      if self.banner_date + 29.days >= self.end_date
        self.end_date
      else 
        self.banner_date + 29.days
      end
    end
  end

  private
  def end_date_is_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "cannot be before the start date") 
    end 
  end

  def announced_date_is_after_end_date
    return if announced_date.blank? || end_date.blank?

    if announced_date < end_date
      errors.add(:announced_date, "cannot be before the end date") 
    end 
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ad, only: [:edit, :update, :destroy]
  before_action :ad_params, only: [:create, :update]
  
  # Create
  def new 
    @ad = Ad.new
  end

  def create
    # debugger
    @ad = Ad.new @ad_params
    @ad.assign_attributes(@banner_option) if params[:banner_option]
    @ad.assign_attributes(@recommend_option) if params[:recommend_option]

    @ad.user = current_user

    if @ad.save
      current_user.user_type = 'client' if current_user.user_type == 'default'
      #current_user.company = @ad.company
      # current_user.businessLicenseNumber = @ad.businessLicenseNumber
      # current_user.phone  = @ad.phone
 

      @hashtags[:name].split('#').reject(&:blank?).each do |tag_name|
        hashtag = Hashtag.find_or_create_by(name: tag_name) 
        @ad.hashtags << hashtag  if not @ad.hashtags.include?(hashtag)
      end
      
      # AlertMailer.ad_create_email(current_user).deliver_now

      redirect_to ads_url
    else
      redirect_to new_ad_url
    end
  end
  
  # Retrieve || Read
  def index 
    @ads = current_user.ads.paginate(:page => params[:page], :per_page => 10)
  end
  
  # Update
  def edit
  end
  
  def update
    if @ad.update @ad_params
      @ad.update(@banner_option)
      @ad.update(@recommend_option)

      redirect_to ads_url
    else
      redirect_to new_ad_url
    end
  end
  
  # Destroy
  def destroy
    @ad.destroy    

    redirect_to ads_url
  end
  
  
  private
  def set_ad 
    @ad = Ad.find params[:id]
    redirect_back(fallback_location: root_path, flash: {danger: "권한이 없습니다."}) if not (current_user == @ad.user)
  end
  
  def ad_params
    if params[:_method].nil?
      if params[:ad_type] == 'event'
        @hashtags = params.require(:event).require(:hashtags).permit(:name)
        @ad_params = params.require(:event).permit(:ad_type,:company, :businessLicenseNumber, :phone,
                                    :method, {detail_method: []} , :announced_link, :announced_date,
                                    :title, {detail_prize: []} , :link, :etc_message, :start_date, :end_date, :img )
                                    
        @banner_option = params.require(:event).permit(:banner_img, :banner_date, :banner_frequency)
        @recommend_option = params.require(:event).permit(:recommend_frequency, :recommend_date)
      elsif params[:ad_type] == 'coupon'
        @hashtags = params.require(:coupon).permit({hashtag: []})
        @ad_params = params.require(:coupon).permit(:ad_type, :company, :businessLicenseNumber, :phone,
                                    :title, {detail_prize: []}, :link, :etc_message, :start_date, :end_date, :img)
                                    
        @banner_option = params.require(:coupon).permit(:banner_img, :banner_date, :banner_frequency)
        @recommend_option = params.require(:coupon).permit(:recommend_frequency, :recommend_date)
      end

    elsif params[:_method] == "patch"
      if @ad.is_ok # 관리자 승인 후 

      else # 관리자 승인 전
        if params[:ad_type] == 'event'
          @hashtags = params.require(:event).permit({hashtag: []})
          @ad_params = params.require(:event).permit(:ad_type, :company, :businessLicenseNumber, :phone,
                                      :title, {detail_prize: []}, :link, :etc_message, :start_date, :end_date, :temp_img)
          
          @banner_option = params[:banner_option] ? params.require(:event).permit(:banner_img, :temp_banner_img, :banner_date, :banner_frequency) : { banner_img: nil, temp_banner_img: nil, banner_date: nil, banner_frequency: nil }
          @recommend_option = params[:recommend_option] ? params.require(:event).permit(:recommend_frequency, :recommend_date) : { recommend_frequency: nil, recommend_date: nil }
        elsif params[:ad_type] == 'coupon'
          @hashtags = params.require(:coupon).permit({hashtag: []})
          @ad_params = params.require(:coupon).permit(:ad_type, :company, :businessLicenseNumber, :phone,
                                      :title, {detail_prize: []}, :link, :etc_message, :start_date, :end_date, :temp_img)
          
          @banner_option = params[:banner_option] ? params.require(:coupon).permit(:banner_img, :temp_banner_img, :banner_date, :banner_frequency) : { banner_img: nil, temp_banner_img: nil, banner_date: nil, banner_frequency: nil }
          @recommend_option = params[:recommend_option] ? params.require(:coupon).permit(:recommend_frequency, :recommend_date) : { recommend_frequency: nil, recommend_date: nil }
        end
      end
    end
  end
end

app/helpers/ads_helper.rb
module AdsHelper
  
end

app/views/ads/_coupon_form.html.erb
<div class="tab-pane fade <%= 'show active' if (@ad.ad_type == 'coupon') %>" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
  <%= form_for ad, as: :coupon do |f| %>
    <input type="hidden" name="ad_type" value="coupon"/>
    <input type="hidden" name="coupon[ad_type]" value="coupon"/>
    <p style="text-align: center; font-family: NanumB; font-size: 18px; margin-top:20px">광고주 정보</p>
    <div class="form-row">
      <div class="form-group col-md-4">
        <%= f.label :company,'주최사' %>
        <%= f.text_field :company, class: "form-control form-control-sm", :required => true %>
      </div> 
      <div class="form-group col-md-4">
        <%= f.label :businessLicenseNumber, '사업자 등록번호' %>
        <%= f.text_field :businessLicenseNumber, class: "form-control form-control-sm", :required => true %>
      </div>
      <div class="form-group col-md-4">
        <%= f.label :phone, '휴대폰 번호' %>
        <%= f.text_field :phone, class: "form-control form-control-sm", placeholder: "- 없이 입력해 주세요.", :required => true %>
      </div>
    </div>
    <p style="text-align: center; font-family: NanumB; font-size: 18px; margin-top: 50px;">광고 정보</p>

    <div class="form-group row">
      <%= f.label :title, '제목', class: "col-sm-2 col-form-label client-label mt-1 mb-1" %>
      <div class="col-sm-10 my-auto"> 
        <%= f.text_field :title, class: "form-control form-control-sm", :required => true %> 
      </div>
      <%= f.label :start_date, '기간', class: "col-sm-2 col-form-label client-label mt-1 mb-1" %>
      <div class="col-sm-4 my-auto">
        <%= f.date_field :start_date, class: "form-control form-control-sm", required: true, disabled: (ad.is_ok?) %> 
      </div>
      <%= f.label :end_date, '~', class: "col-form-labe" %>
      <div class="col-sm-4 my-auto">
        <%= f.date_field :end_date, class: "form-control form-control-sm", required: true, disabled: (ad.is_ok?)  %> 
      </div>

      <div class="w-100 d-none d-block"></div>
    
      <div id="coupon-prize" class="col-sm-12 row pr-0">
        <div class= "col-sm-2 col-form-label client-label">
          <p>경품</p>
          <%=button_tag "+", type: "button", class: "btn btn-outline-dark btn-sm plus" %>
          <%=button_tag "-", type: "button", class: "btn btn-outline-dark btn-sm minus" %>
        </div>
        <div class="col-sm-10 pr-0">
          <% if ad.detail_prize_to_a.empty? %>
            <div class="input-group my-2">
              <div class="input-group-prepend">
                <span class="input-group-text" id="coupon_detail_prize_1" style="height:30px; width: 40px; margin: auto;">1</span>
              </div>
              <input type="text" name="coupon[detail_prize][]" class="form-control" ria-describedby="coupon_detail_method_1" style="height:30px; font-size:14px;"required>
            </div>
          <% else %>
            <% ad.detail_prize_to_a.each_with_index do |method, index| %>
              <div class="input-group my-2">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="coupon_detail_prize_<%=index+1%>" style="height:30px; width: 40px; margin: auto;"><%=index+1%></span>
                </div>
                <input type="text" name="coupon[detail_prize][]" class="form-control" ria-describedby="coupon_detail_method_<%=index + 1%>" style="height:30px; font-size:14px;" value="<%=method%>"required >
              </div>
            <% end %>
          <% end%>
        </div>
      </div>

      <%= f.label 'etc_message', '기타메세지', class:"col-sm-2 client-label"  %>
      <div class="col-sm-10 mb-3">
        <%= f.text_area 'etc_message', rows: "3", class: "form-control", style: "font-size:14px; resize: none;"%>
      </div>
        
      <%= f.fields_for :hashtags do |ff| %>
        <%= ff.label 'name', '해시태그', class:"col-sm-2 client-label mt-2 mb-2" %>
        <div class="col-sm-10 my-auto">
          <%= ff.text_field 'name', value: ad.hashtags.map { |hashtag| hashtag.name}.map { |k| "##{k}" }.join(" "), class:"form-control form-control-sm hashtag hashtag_input", placeholder: "#치킨 #후라이드", :required => true %>
        </div>
      <% end %>

      <% if !ad.img? %>
        <%= f.label :img, '이미지', class: "col-sm-2 client-label mt-2 mb-2"  %>
        <div class="col-sm-10 my-auto">
          <%= f.file_field :img, class: "form-control-file my-auto input_img", style: "height:30px; font-size:14px; padding:2px" %>
        </div>
      <% else %>
        <%= f.label :temp_img, '이미지', class: "col-sm-2 client-label mt-2 mb-2"  %>
        <div class="col-sm-10 my-auto">
          <%= f.file_field :temp_img, class: "form-control-file my-auto input_img", style: "height:30px; font-size:14px; padding:2px" %>
        </div>
        <div class="col-sm-10 offset-sm-2 mb-3">
          <span style="color:red; font-size:12px">*이미지 변경 원할 때 추가해주세요</span>
        </div>
      <% end %>


      <%= render 'option', ad: ad, f:f %>


      <div class="col-sm-12">
        <%= link_to "취소", ads_path, class: "btn btn-outline-dark btn-sm ml-3", style: "float:right" %>
        <%= f.submit "등록", class: "btn btn-outline-dark btn-sm ml-3", style: "float:right" %>
      </div>

    </div>
  <% end %>
</div>

app/views/ads/_event_form.html.erb
<div class="tab-pane fade <%= 'show active' if (@ad.ad_type == 'event' || !@ad.ad_type?) %>" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
  <%= form_for ad, as: :event do |f| %>
    <input type="hidden" name="ad_type" value="event"/>
    <input type="hidden" name="event[ad_type]" value="event"/>
    <p style="text-align: center; font-family: NanumB; font-size: 18px; margin-top:20px">광고주 정보</p>
    <div class="form-row">
      <div class="form-group col-md-4">
        <%= f.label :company,'주최사' %>
        <%= f.text_field :company, class: "form-control form-control-sm", :required => true %>
      </div> 
      <div class="form-group col-md-4">
        <%= f.label :businessLicenseNumber, '사업자 등록번호' %>
        <%= f.text_field :businessLicenseNumber, class: "form-control form-control-sm", :required => true %>
      </div>
      <div class="form-group col-md-4">
        <%= f.label :phone, '휴대폰 번호' %>
        <%= f.text_field :phone, class: "form-control form-control-sm", placeholder: "- 없이 입력해 주세요.", :required => true %>
      </div>
    </div>
    <p style="text-align: center; font-family: NanumB; font-size: 18px; margin-top: 50px;">광고 정보</p>

    <div class="form-group row">
      
      <%= f.label :title, '제목', class: "col-sm-2 col-form-label client-label mt-1 mb-1" %>
      <div class="col-sm-10 my-auto"> 
        <%= f.text_field :title, class: "form-control form-control-sm", :required => true %> 
      </div>
      <%= f.label :method, '방법', class: "col-sm-2 col-form-label client-label mt-1 mb-1" %>
      <div class="col-sm-5 my-auto"> 
        <%= f.text_field :method, class: "form-control form-control-sm", :required => true %> 
      </div>
      <div class="w-100 d-none d-block"></div>

      <%= f.label :link, '링크', class: "col-sm-2 col-form-label client-label mt-1 mb-1" %>
      <div class="col-sm-10 my-auto"> 
        <%= f.text_field :link, class: "form-control form-control-sm", :required => true %> 
      </div>
      
      <%= f.label :announced_link, '발표 링크', class: "col-sm-2 col-form-label client-label mt-1 mb-1" %>
      <div class="col-sm-10 my-auto"> 
        <%= f.text_field :announced_link, class: "form-control form-control-sm", :required => true %> 
      </div>

      <%= f.label :start_date, '기간', class: "col-sm-2 col-form-label client-label mt-1 mb-1" %>
      <div class="col-sm-4 my-auto">
        <%= f.date_field :start_date, class: "form-control form-control-sm", required: true, disabled: (ad.is_ok?) %> 
      </div>
      <%= f.label :end_date, '~', class: "col-form-labe" %>
      <div class="col-sm-4 my-auto">
        <%= f.date_field :end_date, class: "form-control form-control-sm", required: true, disabled: (ad.is_ok?)  %> 
      </div>
      <%= f.label :announced_date, '당첨자 발표일', class: "col-sm-2 col-form-label client-label mt-1 mb-1" %>
      <div class="col-sm-4 my-auto">
        <%= f.date_field :announced_date, class: "form-control form-control-sm", required: true %> 
      </div>

      <div class="w-100 d-none d-block"></div>
      <div id="event-methods" class="col-sm-12 row pr-0">
        <div class= "col-sm-2 col-form-label client-label">
          <p>응모 방법</p>
          <%=button_tag "+", type: "button", class: "btn btn-outline-dark btn-sm plus" %>
          <%=button_tag "-", type: "button", class: "btn btn-outline-dark btn-sm minus" %>
        </div>
        <div class="col-sm-10 pr-0">
          <% if ad.detail_method_to_a.empty? %>
            <div class="input-group my-2">
              <div class="input-group-prepend">
                <span class="input-group-text " id="event_detail_method_1" style="height:30px; width: 40px; margin: auto;">1</span>
              </div>
              <input type="text" name="event[detail_method][]" class="form-control" ria-describedby="event_detail_method_1" style="height:30px; font-size:14px;" required>
            </div>
          <% else %>
            <% ad.detail_method_to_a.each_with_index do |method, index| %>
              <div class="input-group my-2">
                <div class="input-group-prepend">
                  <span class="input-group-text " id="event_detail_method_<%=index+1%>" style="height:30px; width: 40px; margin: auto;"><%=index+1%></span>
                </div>
                <input type="text" name="event[detail_method][]" class="form-control" ria-describedby="event_detail_method_<%=index + 1%>" style="height:30px; font-size:14px;" value="<%=method%>" required>
              </div>
            <% end %>
          <% end%>
        </div>
      </div>

      <div id="event-prize" class="col-sm-12 row pr-0">
        <div class= "col-sm-2 col-form-label client-label">
          <p>경품</p>
          <%=button_tag "+", type: "button", class: "btn btn-outline-dark btn-sm plus" %>
          <%=button_tag "-", type: "button", class: "btn btn-outline-dark btn-sm minus" %>
        </div>
        <div class="col-sm-10 pr-0">
          <% if ad.detail_prize_to_a.empty? %>
            <div class="input-group my-2">
              <div class="input-group-prepend">
                <span class="input-group-text" id="event_detail_prize_1" style="height:30px; width: 40px; margin: auto;">1</span>
              </div>
              <input type="text" name="event[detail_prize][]" class="form-control" ria-describedby="event_detail_method_1" style="height:30px; font-size:14px;"required>
            </div>
          <% else %>
            <% ad.detail_prize_to_a.each_with_index do |method, index| %>
              <div class="input-group my-2">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="event_detail_prize_<%=index+1%>" style="height:30px; width: 40px; margin: auto;"><%=index+1%></span>
                </div>
                <input type="text" name="event[detail_prize][]" class="form-control" ria-describedby="event_detail_method_<%=index + 1%>" style="height:30px; font-size:14px;" value="<%=method%>"required >
              </div>
            <% end %>
          <% end%>
        </div>
      </div>

      <%= f.label 'etc_message', '기타메세지', class:"col-sm-2 client-label"  %>
      <div class="col-sm-10 mb-3">
        <%= f.text_area 'etc_message', rows: "3", class: "form-control", style: "font-size:14px; resize: none;"%>
      </div>
        
      <%= f.fields_for :hashtags do |ff| %>
        <%= ff.label 'name', '해시태그', class:"col-sm-2 client-label mt-2 mb-2" %>
        <div class="col-sm-10 my-auto">
          <%= ff.text_field 'name', value: ad.hashtags.map { |hashtag| hashtag.name}.map { |k| "##{k}" }.join(" "), class:"form-control form-control-sm hashtag hashtag_input", placeholder: "#치킨 #후라이드", :required => true %>
        </div>
      <% end %>

      <% if !ad.img? %>
        <%= f.label :img, '이미지', class: "col-sm-2 client-label mt-2 mb-2"  %>
        <div class="col-sm-10 my-auto">
          <%= f.file_field :img, class: "form-control-file my-auto input_img", style: "height:30px; font-size:14px; padding:2px" %>
        </div>
      <% else %>
        <%= f.label :temp_img, '이미지', class: "col-sm-2 client-label mt-2 mb-2"  %>
        <div class="col-sm-10 my-auto">
          <%= f.file_field :temp_img, class: "form-control-file my-auto input_img", style: "height:30px; font-size:14px; padding:2px" %>
        </div>
        <div class="col-sm-10 offset-sm-2 mb-3">
          <span style="color:red; font-size:12px">*이미지 변경 원할 때 추가해주세요</span>
        </div>
      <% end %>

      <%= render 'option', ad: ad, f:f %>


      <div class="col-sm-12">
        <%= link_to "취소", ads_path, class: "btn btn-outline-dark btn-sm ml-3", style: "float:right" %>
        <%= f.submit "등록", class: "btn btn-outline-dark btn-sm ml-3", style: "float:right" %>
      </div>

    </div>
  <% end %>
</div>

app/views/ads/_form.html.erb
<div class="row">
  <div class="col-2">
    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
      <%= link_to 'EVENT', '#v-pills-home', 
                  class: "nav-link #{'active' if @ad.ad_type == 'event' || !@ad.ad_type? }", id:"v-pills-home-tab", 
                  "data-toggle" => "pill", "role" => "tab", "aria-controls"=>"v-pills-home", "aria-selected" => true if @ad.ad_type == 'event' || !@ad.ad_type? %>
      <%= link_to 'COUPON', '#v-pills-profile', 
                    class: "nav-link #{'active' if @ad.ad_type == 'coupon' }", id:"v-pills-profile-tab", 
                    "data-toggle" => "pill", "role" => "tab", "aria-controls"=>"v-pills-profile", "aria-selected" => false if @ad.ad_type == 'coupon' || !@ad.ad_type? %>

     </div>
  </div>
  <div class="col-9">
    <div class="tab-content" id="v-pills-tabContent">
      <%= render 'event_form', ad: ad if (@ad.ad_type == 'event' || !@ad.ad_type?) %>
      <%= render 'coupon_form', ad: ad if (@ad.ad_type == 'coupon' || !@ad.ad_type?) %>
    </div>
  </div>
</div>

app/views/ads/edit.html.erb
<div class="container">
  <div class="row" style="margin-bottom:110px;">
    <%= render '/shared/sub_title', title: 'ADVERTISE', sub_title: '광고 등록 - EDIT'%>
    <div class="col-md-10 offset-md-1" stayle="margin:auto;">
      <%= render 'form', ad: @ad %>
    </div>
  </div>
</div>

app/views/ads/index.html.erb
<div class="container">
  <div class="row" >
    <%= render '/shared/sub_title', title: 'ADVERTISE', sub_title: '등록한 광고'%>
    <main role="main" class="col-md-11" style="margin: 0px auto 20px auto;font-size:14px">
      <div class="row" style="font-size:16px">
        <p style="text-align:left; color:black;font-family:NanumB; margin:0px 0px 16px 0px;">이용자 정보</p>
        <div class="col-sm-12">
          <p>이메일 : <%= current_user.email%></p>
        </div>
      <div class="table-responsive" style="overflow-x:unset">
        <table class="table table-hover">
          <thead>
            <tr>
              <th style="width:5%"></th>
              <th style="width: 10%">등록 예정일</th>
              <th style="width: 55%">제목</th>
              <th style="width: 10%">승인 여부</th>
              <th style="width: 10%">수정</th>
              <th style="width: 10%">삭제</th>
            </tr>
          </thead>
          <tbody>
          
            <% @ads.each do |ad|%>
              <tr>
                <th scope="row"><button class="btn btn-outline-info btn-sm mt-1 btn_client_info">tag 보기</button></th>
                <td><%=ad.start_date.in_time_zone("Seoul").strftime("%m/%d")%></td>
                <td data-toggle="modal" data-target="#adModal" data-whatever="<%=ad.class.name%>/<%=ad.id%>" style="cursor: pointer;"><%= ad.title %></td>
                <td><%= ad.is_ok ? "예" : "아니오" %></td>
                <td>
                  <%= link_to "수정", edit_ad_path(ad), class: "btn btn-outline-danger btn-sm" %>
                </td>
                <td>
                <% if ad.is_ok %>
                email 문의
                <% else %>
                  <%= link_to "x", ad_path(ad), class: "btn btn-outline-danger btn-sm", method: :delete,data: { confirm: '정말 삭제할까요?' } %>
                <% end %>
                </td>
              </tr>
              <tr class="client_info" style="display:none; background-color:#8080805e">
                <td></td>
                <td class="p-1"colspan="5" style="text-align:left; padding-left:12px !important;">
                  <% ad.hashtags.each do |tag|%>
                  #<%= tag.name %>
                  <% end %>
                </td>
              </tr>
            <% end %>
            
          </tbody>
          <tfoot>
            <tr>
              <td colspan="6" style="border-bottom: 1px solid #dee2e6;padding:11px; position:relative">
                <div class="digg_pagination d-flex justify-content-center" style="height:27px;">
                  <%= will_paginate @events, :container => false %>
                </div>
                <%= link_to  "등록", new_ad_path, class: "btn btn-outline-dark btn-sm", style: "position:absolute;top:8px;right:8px;" %>
              </td>
            </tr>
          </tfoot>
        </table> 
        <div class="digg_pagination d-flex justify-content-center">
        </div>
      </div>
      
      </div>
    </main>
  </div>
</div>

app/views/ads/new.html.erb
<div class="container">
  <div class="row" style="margin-bottom:110px;">
    <%= render '/shared/sub_title', title: 'ADVERTISE', sub_title: '광고 등록'%>
    <div class="col-md-10 offset-md-1" stayle="margin:auto;">
      <%= render 'form', ad: @ad %>
    </div>
  </div>
</div>