config/routes.rb
Rails.application.routes.draw do
  get '/refresh' => 'main#refresh'
  root 'main#index'
  get '/modal_content/:type/:id' => 'main#modal_content'

  get '/d_day', to: 'main#d_day'
  get '/search', to: "main#search"
  
  post '/ad_like/:ad_id', to: 'likes#like_toggle'

  resources :market_posts do
    resources :market_comments, only: [:create, :destroy]
  end
  post '/market_posts/:market_post_id/reply/:id', to: 'market_comments#reply', as: 'market_post_reply'


  resources :ads, except: [:show]


  get '/intro', to: 'main#intro'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'} 

  get 'managers/my_adballoon', to: 'managers#my_adballoon'

  get 'managers/index', to: 'managers#index'
  get 'managers/ad_list', to: 'managers#ad_list'
  get 'managers/user_list', to: 'managers#user_list'
  
  get 'managers/ads/:id', to: 'managers#ads_edit', as: 'managers_ads'
  patch 'managers/ads/:id', to: 'managers#ads_update'
  delete 'managers/ads/:id', to: 'managers#ads_delete'

  post 'managers/ad_img/:id', to: 'managers#img_update', as: 'managers_img'
  post 'managers/ad_toggle/:id', to: 'managers#ad_toggle', as: 'managers_ad_toggle'

  get 'managers/main'
  post 'managers/main_update/:type', to: 'managers#main_update'
  post 'managers/ad_check/:id', to: 'managers#ad_check'
  post 'managers/img_update/:id', to: 'managers#img_update'
  delete 'managers/ads_delete/:id', to: 'managers#ads_delete'
end

app/models/market_post.rb
class MarketPost < ApplicationRecord
  mount_uploader :img, ImgUploader
  belongs_to :user
  has_many :market_comments, dependent: :delete_all

  validates :post_type, presence: true,
                        inclusion: { in: ["buy", "sell"] }
  validates :title, presence: true,
                    length: { maximum: 30, minimum: 2 }
  validates :content, presence: true,
                      length: { maximum: 65536, minimum: 10 }
  
  # validates :img

end

app/controllers/market_posts_controller.rb
class MarketPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_market_post, only: [:edit, :update, :destroy]
  
  def new 
    @market_post = MarketPost.new
  end

  def create
    market_post_params = params.require(:market_post).permit(:post_type, :title, :content)
    @market_post = MarketPost.new market_post_params
    @market_post.user = current_user

    if @market_post.save
      redirect_to market_post_path(@market_post), { flash: {success: '등록 되었습니다.'} }
    else
      flash[:danger] = '실패하였습니다.'
      redirect_back(fallback_location: root_path)
    end
  end

  def show
    @market_post = MarketPost.find(params[:id])
  end

  def index
    @recommends = recommends
    if params[:type].nil?
      @market_posts = MarketPost.all
    elsif params[:type] == 'sell'
      @market_posts = MarketPost.where(post_type: "sell")
    elsif params[:type] == 'buy'
      @market_posts = MarketPost.where(post_type: "buy")
    end
    @market_posts = @market_posts.where("#{params[:search_type]} LIKE ?", "%#{params[:serach]}%") if params[:search_type]
    @market_posts = @market_posts.paginate(page: params[:page], per_page: 10) 
  end
  
  def edit
  end

  def update
    market_post_params = params.require(:market_post).permit(:title, :content)
  
    if @market_post.update market_post_params
      redirect_to market_post_path(@market_post), { flash: {success: '수정 되었습니다.'} }
    else
      flash[:danger] = '실패하였습니다.'
      redirect_back(fallback_location: root_path)
    end
  end
  
  def destroy
    @market_post.destroy
    redirect_to market_posts_path, { flash: {success: '삭제 되었습니다.'} }
  end
  
  private
  def set_market_post 
    @market_post = MarketPost.find params[:id]
    redirect_back(fallback_location: root_path, flash: {danger: "권한이 없습니다."}) if (current_user != @market_post .user)
  end

end

app/helpers/market_posts_helper.rb
module MarketPostsHelper
end

app/views/market_posts/_form.html.erb
<div class="container-fluid" style="background-color:#F7F7F7; min-height: 100vh;">
  <div class="row" style="width:1200px; margin:auto;padding-bottom:200px;">
    <div class="col-md-12 d-flex justify-content-center mt-4">
      <div>
        <p style="text-align:center; color:black;font-family:NanumB; margin:16px 0px 16px 0px;">
          <%= market_post.new_record? ? '글작성' : '수정' %>
        </p>
        <hr style="width:300px;border-top: 1px solid rgba(0,0,0,.1);">
      </div>
    </div>
    <div class="col-md-10 offset-md-1">
      <%= form_for market_post do |f| %>
        <div class="form-group row">
          <div class="col-sm-2">  
            <%= f.select(:post_type, [['삽니다', 'buy'], ['팝니다','sell']], {}, { class: 'form-control form-control-sm', disabled: (!market_post.new_record?) }) %>
          </div>
          <div class="col-sm-10" style="margin: auto;" >
            <%= f.text_field :title, class: "form-control form-control-sm", placeholder: "제목", required:true%>
          </div>

          <div class="col-sm-12 mt-3" style="margin: auto;" >
            <%= f.text_area :content, class: "tinymce", rows: 18, cols: 120 %>
            <%= tinymce %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-2 offset-sm-10" style="text-align:right">
            <%= f.submit '등록', class: "btn btn-outline-dark btn-sm ml-3", style: "display:inline-block" %>
            <%= link_to '취소', market_posts_path, class: "btn btn-outline-dark btn-sm ml-3", style: "display:inline-block" , "data-confirm" => "정말 취소하시겠습니까?"%>
          </div>
        </div>
      <% end %>
    </div>    
  </div>  
</div>

app/views/market_posts/edit.html.erb
<%= render 'form', market_post: @market_post %>

app/views/market_posts/index.html.erb
<%= render '/shared/recommend', recommends: @recommends if !@recommends.empty? %>

<div class="container-fluid" style="background-color:#F7F7F7; ">
  <div class="row" style="width:1200px; margin:auto;padding-bottom:200px;">
    <div class="col-md-12 d-flex justify-content-center mt-4">
      <div>
        <h2 class="text-center">AD MAKET</h2>
        <hr style="width:300px;border-top: 1px solid rgba(0,0,0,.1);">
      </div>
    </div>
    <main role="main" class="col-md-11" style="margin: 0px auto 20px auto;font-size:14px;">
      <div class="table-responsive" style="overflow-x: unset;">
        <p style="color:black;font-family:NanumB; margin:16px 0px 16px 0px;">
          <%= link_to '전체', market_posts_path, class: "category #{'category_active' if params[:type].nil?}" %>
          <%= link_to '삽니다', market_posts_path(type:"buy"), class: "category #{'category_active' if params[:type] == "buy"}" %>
          <%= link_to '팝니다', market_posts_path(type:"sell"), class: "category #{'category_active' if params[:type] == "sell"}" %>
        </p>
        <table class="table table-hover">
          <thead>
            <tr>
              <th style="width: 5%; text-align:center;">No</th>
              <th style="width: 10%"></th>
              <th style="width: 65%">제목</th>
              <th style="width: 10%;text-align:center;">작성자</th>
              <th style="width: 10%; text-align:center;">날짜</th>
            </tr>
          </thead>
          <tbody>
          <% if !@market_posts.nil?%>
            <% @market_posts.reverse.each do |post|  %>
             <tr style="cursor:pointer;"  onClick="location.href='<%= market_post_path(post) %>'">
                <th scope="row" style="text-align:center;"><%=post.id%></th>
                <td>[<%= post.post_type == "buy" ? '삽니다' : '팝니다' %>]</td>
                <td><%=post.title%> <span >(<%=post.market_comments.size%>)<span></td>
                <td style="text-align:center;"><%=post.user.email.split('@')[0]%></td>
                <td style="text-align:center;"><%=post.created_at.utc.in_time_zone("Seoul").strftime("%m-%d")%></td>
              </tr>
            <% end %>
            <% end%>
          </tbody>
          <tfoot>
            <tr>
              <td colspan="5" style="border-bottom: 1px solid #dee2e6;padding:11px; position:relative">
                <div class="digg_pagination d-flex justify-content-center" style="height:27px;">
                  <%= will_paginate @market_posts, :container => false %>
                </div>
                <%= link_to '등록', new_market_post_path(pre: params[:type]), class: "btn btn-outline-dark btn-sm", style: "position:absolute;top:8px;right:8px;" %>
              </td>
            </tr>
            <tr>
              <td colspan="4" style="padding: 12px 20%;">
              <form action="/market_posts" method="get" >
                <input type="hidden" name="type" value="<%=params[:type]%>">
                <div class="input-group mb-3">
                  <select name="search_type" class="form-control form-control-sm" style="flex:0.2; ">
                    <option value="title">제목</option>
                    <option value="content">내용</option>
                  </select>
                  <input type="text" name="search"class="form-control  form-control-sm" required>
                  <button type="submit" class="btn btn-outline-dark btn-sm ml-3 mr-3">검색</button>
                </div>
              </form>
              </td>
            </tr>
          </tfoot>
        </table> 
        <div class="digg_pagination d-flex justify-content-center">
          
        </div>
      </div>
    </main>
    
  </div>  
</div>

app/views/market_posts/new.html.erb
<%= render 'form', market_post: @market_post %>

app/views/market_posts/show.html.erb
<div class="container-fluid" style="background-color:#F7F7F7; padding-top: 44px; ">
  <div class="row" style="width:1200px; margin:auto;padding-bottom:20px;">
    <div class="col-sm-12 d-flex justify-content-center mt-4">
      <div>
        <p style="text-align:center; color:black;font-family:NanumB; margin:16px 0px 16px 0px;">
        AD MARKET
        </p>
        <hr style="width:300px;border-top: 1px solid rgba(0,0,0,.1);">
      </div>
    </div>
    <div class="col-sm-10 offset-sm-1 row" style="border-top: 2px solid red; padding-top: 10px;">
      <div class="col-sm-1 pb-2" style="border-bottom: 1px solid rgba(0,0,0,.1);"><p style="text-align:right; margin:0px;">제목</p></div>
      <div class="col-sm-11 pb-2" style="border-bottom: 1px solid rgba(0,0,0,.1);">[<%= @market_post.post_type == "buy" ? '삽니다' : '팝니다' %>] <%=@market_post.title%></div>
      <div class="col-sm-12 pt-2 pb-2" >
        <%=@market_post.user.email%>
        <span style="border-left: 1px solid rgba(0,0,0,.1);margin-right: 10px;margin-left: 5px;"></span>
        <%=@market_post.created_at.utc.in_time_zone("Seoul").strftime("%Y-%m-%d")%>
      </div>
      <div class="col-sm-12 mb-3" style="min-height:300px;border-top: 1px solid rgba(0,0,0,.1);padding-top:10px">
        <%=@market_post.content.html_safe%>
      </div>

    


     
      <div class="col-sm-5 offset-sm-7 mt-3 mb-3" style="text-align:right">
        <% if current_user == @market_post.user || current_user.user_type == "manager"%>
          <%= link_to '수정', edit_market_post_path(@market_post), class: "btn btn-outline-dark btn-sm ml-3" %>
          <%= link_to '삭제', market_post_path(@market_post), class: "btn btn-outline-dark btn-sm ml-3", method: :delete, "data-confirm" => "정말 삭제하시겠습니까?" %>
        <% end %>
        <%= link_to '목록', market_posts_path, class: "btn btn-outline-dark btn-sm ml-3"%>
      </div>
      


      <div class="col-sm-12 py-2 mb-4 px-0" style="border: 1px solid rgba(0,0,0,.1); border-radius: 5px;">
        <p class="m-2">코멘트(<%=@market_post.market_comments.size%>)</p>
          <% @market_post.market_comments.where("reply_comment_id IS NULL").each do |comment| %>
            <div>
              <div class="mx-2 px-2 py-3" style="border-top:1px dotted rgba(0,0,0,.1); position:relative;"> 
              <% if !comment.isSecret || @market_post.user.id == current_user.id || comment.user.id ==  current_user.id || current_user.user_type == "manager"%>
                <p class="m-1" style="font-family:NanumB;">
                  <span style="background-color:black;padding:2px; border-radius: 12px;"><img style="margin:auto" src="<%= image_path('icon/login_fill.png') %>" alt="icon_login" height='17px' /></span>
                  <%= comment.user.email %>
                  <% if comment.isSecret %>
                    <img style="margin:auto" src="<%= image_path('icon/secret.png') %>" alt="icon_secret" height='17px' />
                  <% end %>
                </p>
                <p class="m-2 pr-5">
                  <%= comment.content %>
                  <span style="padding-left:10px;font-size:12px;opacity:0.5;color: rgb(138, 131, 126) !important;"><%= comment.created_at.in_time_zone("Seoul").strftime("%y.%m.%d %H:%M")%></span>
                </p>
                  <button type="button" class="btn btn-outline-dark btn-sm btn_reply" style="position:absolute; right:8px; bottom: 16px;">답글</button>       
                  <%= link_to 'X', market_post_market_comment_path(@market_post, comment), method: :delete, "data-confirm" => "정말 삭제하시겠습니까?", class: "btn btn-outline-dark btn-sm", style: "position:absolute; right:8px; top: 8px;"  if comment.user.id == current_user.id || current_user.user_type == "manager" %>
              <% else %>
                <p class="m-2 pr-5">
                  비밀 댓글 입니다.
                  <span style="padding-left:10px;font-size:12px;opacity:0.5;color: rgb(138, 131, 126) !important;"><%= comment.created_at.in_time_zone("Seoul").strftime("%y.%m.%d %H:%M")%></span>
                </p>
              <% end %>
              </div>
              
              <% MarketComment.where(reply_comment_id: comment.id).each do |reply| %>
                <div class="py-2" style="border-top:1px dotted rgba(0,0,0,.1); background-color: #8c8c8c61;display: flex;justify-content: center;align-items: end;">
                  <div style="display:inline-block;width:5%; text-align:right;">ㄴ</div>
                  <% if @market_post.user.id == current_user.id || reply.user.id ==  current_user.id || current_user.user_type == "manager" %>
                    <div class="p-1" style="width:90%; display:inline-block">  
                      <p class="m-1" style="font-family:NanumB;">
                        <span style="background-color:black;padding:2px; border-radius: 12px;"><img style="margin:auto" src="<%= image_path('icon/login_fill.png') %>" alt="icon_login" height='17px' /></span>
                        <%= reply.user.email %>
                        <!--<img style="margin:auto" src="<%= image_path('icon/secret.png') %>" alt="icon_secret" height='17px' />-->
                      </p>
                      <p class="m-2 pr-5">
                        <%= reply.content %>
                        <span style="padding-left:10px;font-size:12px;opacity:0.5;color: rgb(138, 131, 126) !important;"><%= reply.created_at.in_time_zone("Seoul").strftime("%y.%m.%d %H:%M")%></span>
                      </p>
                      
                    </div>
                    <%= link_to 'X', market_post_market_comment_path(@market_post, reply), method: :delete, "data-confirm" => "정말 삭제하시겠습니까?", class: "btn btn-outline-dark btn-sm", style: "padding: 0px 7px;"  if comment.user.id == current_user.id || current_user.user_type == "manager" %>
           
                  <% else %>
                  <div class="p-1" style="width:90%; display:inline-block">  
                      <p class="m-2 pr-5">
                        비밀 댓글입니다.
                        <span style="padding-left:10px;font-size:12px;opacity:0.5;color: rgb(138, 131, 126) !important;"><%= reply.created_at.in_time_zone("Seoul").strftime("%y.%m.%d %H:%M")%></span>
                      </p>
                    </div>
                  <% end %>
                </div>
              <% end %>
                
              <div class="mx-auto my-3 reply_form" style="display:none">
                <div style="display:inline-block;width:5%; text-align:right;">ㄴ</div>
                <form action='<%=market_post_reply_path(@market_post, comment)%>' method='post' style="display:inline-block;width:90%; background-color:white;border: 1px solid #ced4da;border-radius: .25rem;">
                  <input type="hidden" name="authenticity_token", value = "<%=form_authenticity_token %>">      
                  <div class="form-group row">
                    <div class="col-sm-11" style="margin: auto;" >
                      <div class="m-2 p-1" style="font-family:NanumB;font-size:11px;display:inline-block;">
                        <span style="background-color:black;padding:2px; border-radius: 12px;"><img style="margin:auto" src="<%= image_path('icon/login_fill.png') %>" alt="icon_login" height='12px' /></span>
                        <%= current_user.email%><span style="color:blue; padding-left:5px;">(<% if current_user.id == @market_post.user.id%>글쓴이<%else%>댓글은 글쓴이만 보입니다.<%end%>)</span>
                      </div>
                      <div class="form-check m-2" style="display:none;font-size:13px;"> <!-- inline-block -->
                        <input class="form-check-input" type="checkbox" value="true" id="is_secret" name="is_secret" checked>
                        <label class="form-check-label" for="is_secret">비밀댓글</label>
                      </div>
                      <textarea class="form-control" name="marekt_content" rows="3" style="width:94%; margin-left:3%; margin-right:3%; resize: none;border: 0px solid #ced4da;" placeholder="댓글을 입력해주세요"></textarea>
                    </div>
                    <div class="col-sm-1 p-0" >
                        <button type="submit" class="btn btn-outline-dark btn-sm" style="display:inline-block;position:absolute; bottom:0px">등록</button>                 
                    </div>
                  </div>
                </form>
              </div>

            </div>  
          <% end %>
      </div>
    </div>


    <div class="col-sm-10 offset-sm-1 ">
      <form action='<%=market_post_market_comments_path(@market_post)%>' method='post' style="background-color:white;border: 1px solid #ced4da;border-radius: .25rem;">
        <input type="hidden" name="authenticity_token" value = "<%=form_authenticity_token %>">      
        <div class="form-group row">
          <div class="col-sm-11" style="margin: auto;" >
            <div class="m-2 p-1" style="font-family:NanumB;font-size:11px;display:inline-block;">
              <span style="background-color:black;padding:2px; border-radius: 12px;"><img style="margin:auto" src="<%= image_path('icon/login_fill.png') %>" alt="icon_login" height='12px' /></span>
              <%= current_user.email%><span style="color:blue; padding-left:5px;">(<% if current_user.id == @market_post.user.id%>글쓴이<%else%>댓글은 글쓴이만 보입니다.<%end%>)</span>
            </div>
            <div class="form-check m-2" style="display:none;font-size:13px;"> <!-- inline-block -->
              <input class="form-check-input" type="checkbox" value="true" id="is_secret" name="is_secret" checked>
              <label class="form-check-label" for="is_secret">비밀댓글</label>
            </div>
            <textarea class="form-control" name="marekt_content" rows="3" style="width:94%; margin-left:3%; margin-right:3%; resize: none;border: 0px solid #ced4da;" placeholder="댓글을 입력해주세요"></textarea>
          </div>
          <div class="col-sm-1 p-0" >
              <button type="submit" class="btn btn-outline-dark btn-sm" style="display:inline-block;position:absolute; bottom:0px">등록</button>                 
          </div>
        </div>
      </form>
    </div>
  </div>  
</div>