config/routes.rb
Rails.application.routes.draw do
  get '/refresh' => 'main#refresh'
  root 'main#index'
  get '/modal_content/:type/:id' => 'main#modal_content'

  get '/d_day', to: 'main#d_day'
  get '/search', to: "main#search"
  
  post '/ad_like/:ad_id', to: 'likes#like_toggle'

  resources :market_posts do
    resources :market_comments, only: [:create, :destroy]
  end
  post '/market_posts/:market_post_id/reply/:id', to: 'market_comments#reply', as: 'market_post_reply'


  resources :ads, except: [:show]


  get '/intro', to: 'main#intro'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'} 

  get 'managers/my_adballoon', to: 'managers#my_adballoon'

  get 'managers/index', to: 'managers#index'
  get 'managers/ad_list', to: 'managers#ad_list'
  get 'managers/user_list', to: 'managers#user_list'
  
  get 'managers/ads/:id', to: 'managers#ads_edit', as: 'managers_ads'
  patch 'managers/ads/:id', to: 'managers#ads_update'
  delete 'managers/ads/:id', to: 'managers#ads_delete'

  post 'managers/ad_img/:id', to: 'managers#img_update', as: 'managers_img'
  post 'managers/ad_toggle/:id', to: 'managers#ad_toggle', as: 'managers_ad_toggle'

  get 'managers/main'
  post 'managers/main_update/:type', to: 'managers#main_update'
  post 'managers/ad_check/:id', to: 'managers#ad_check'
  post 'managers/img_update/:id', to: 'managers#img_update'
  delete 'managers/ads_delete/:id', to: 'managers#ads_delete'
end

app/views/layouts/_header.html.erb
<div class="ad-nav" style="background-color:#212529d1!important; position:fixed; top:0px; width:100%; height:44px; z-index: 999;">
  <div class="container" style="height:100%">
    <ul class="nav-list d-flex justify-content-between" style="text-align:center;height:100%; font-size:14px;padding-right:40px">
      <li class="nav-item d-flex align-items-center">
        <%= link_to image_tag("logo2.png", alt: "icon_logo", height:'27px'), root_path %>
      </li> 
      <li class="nav-item d-none d-sm-flex align-items-center nav-d-day">
        <%= link_to 'D-DAY', '/d_day', class: "nav-ink", style: "color:white !important; width:100px; text-decoration: none !important;" %>
      </li>
      <li class="nav-item d-none d-sm-flex align-items-center nav-market dropdown" style="font-size: 12px">
        <div class="nav-market-name"style="text-align:center; cursor: pointer; color:white !important;  width:100px; margin:auto"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">AD MARKET</div>
        <div class="dropdown-menu" aria-labelledby="adMarket" style="">
          <%= link_to '삽니다', market_posts_path(type: 'buy'), class: 'dropdown-item',  style: "color:white !important; text-align:center; text-decoration: none !important;" %>
          <%= link_to '팝니다', market_posts_path(type: 'sell'), class: 'dropdown-item',  style: "color:white !important; text-align:center; text-decoration: none !important;" %>
        </div>
      </li>
     <li class="nav-item d-none d-sm-flex align-items-center nav-client dropdown">
        <div class="nav-market-advertise"style="text-align:center; cursor: pointer; color:white !important;  width:100px; margin:auto"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">ADVERTISE</div>
        <div class="dropdown-menu" aria-labelledby="adMarket" style="">
          <%#= link_to '소개', '/intro', class: 'dropdown-item',  style: "color:white !important; text-align:center; text-decoration: none !important;" %>
          <%= link_to '등록', ads_path, class: 'dropdown-item',  style: "color:white !important; text-align:center; text-decoration: none !important;" %>
          <%#= link_to '문의사항', services_path, class: 'dropdown-item',  style: "color:white !important; text-align:center; text-decoration: none !important;" %>
        </div>
      </li>
  
      <li class="d-flex align-items-center nav-search-bar" style="display:none !important">
        <form action="/search" method="GET" class="d-flex align-items-center nav-search-form">
          <input class="hashtag_input" type="text" name="keyword" placeholder="#치킨 #후라이드" autocomplete="off" />
          <button type="submit" aria-label="제출" style="outline: none;"disabled> </button>
        </form>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item d-none d-sm-flex align-items-center nav-login dropdown" style="width:100px;">
          <img style="margin:auto" src="<%= image_path('icon/login_fill.png') %>" alt="icon_login" height='17px'  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" />
          <div class="dropdown-menu" aria-labelledby="dropdownMenu2" style="min-width: 7rem;">
            <%= link_to 'My Adballoon', managers_my_adballoon_path, class: "dropdown-item",style: "text-align:center; color:white !important;"  %>
            <%= link_to '관리하기',  managers_index_path, class: "dropdown-item",style: "text-align:center; color:white !important;"  if current_user.user_type == 'manager'%>
            <%= link_to '로그아웃', destroy_user_session_path, method: :delete, class: "dropdown-item",style: "text-align:center; color:white !important;" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item d-none d-sm-flex align-items-center nav-login" style="width:100px;">
          <%= link_to image_tag("icon/login.png", alt: "icon_login", height:'17px', style:"margin:auto"), new_user_session_path, class: 'nav-link', style: "margin: auto; color:white !important;" %>
        </li>  
      <% end %>

      <li class="nav-item d-flex align-items-center nav-icon-search">
      </li>
      <!--<li class="nav-item d-sm-none d-flex align-items-center">
        목록
      </li>-->
    </ul>
  </div>
</div>

<div class="search-bg">
  <div class="recommend_tag" style="background-color:white; width:0px; height:150px; margin:44px auto; display:none;">
    <p style="color: #888; font-size:10px;">인기 태그</p>
    <% @hashtags.each do |tag|%>
      <span>#<%= tag[:name] %><span style="font-size:10px;">(<%=tag[:count]%>)</span> </span>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adballon</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= yield :js %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <div style="margin-top: 44px;">
      <%= yield %>

      <div class="modal fade" id="adModal" data-backdrop='static' tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" >
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document" >
          <div class="modal-content">
            <div id="loading" class="spinner" style=" margin:295px auto;">
              <div class="bounce1"></div>
              <div class="bounce2"></div>
              <div class="bounce3"></div>
            </div>
            <div class="modal-body" id="my-modal-body">
            </div>
          </div>
        </div>
      </div>
    </div>

      <!--<i id="btn_top">
        <img src="<%= image_path('icon/top.png') %>" alt="btn_top" height='20px' style="width:30px;height:30px;cursor:pointer"/>
      </i>-->


    <section style="background: #f2f2f2; padding:10px 15%; width: 100%;">
      <!-- <p style="color:black; font-size:10px; margin:16px 0px 0px 0px;"><span style=" font-size:11px;">공지사항 :</span> 상세 문의는 메일로 문의해주세요</p>-->
      <hr>
      <p style="color:#888; font-size:10px">Copyright © 2018 *****. 모든 권리 보유.</p>
      <p style="color:#888; font-size:10px">사업자등록번호 : ***-**-***** | 통신판매업신고번호 : 제 0000-****-00000호 | 대표이사 : *** | 주소 : ** *** *** ***** | 대표전화 : 00-0000-0000 | 팩스 : 00-0000-0000</p>
      <hr>
    </section>

    <div class="modal fade" id="adModal" data-backdrop='static' tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" >
      <div class="modal-dialog modal-dialog-centered modal-lg" role="document" >
        <div class="modal-content">
          <div id="loading" class="spinner" style=" margin:295px auto;">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
          </div>
          <div class="modal-body" id="my-modal-body">
          </div>
        </div>
      </div>
    </div>
    <% flash.each do |k, v| %>
      <%= render '/shared/alert', k: k, v: v %>
    <% end %>
  </body>
</html>